#!/bin/bash
ln -Tfs /usr/share/backgrounds/linuxmint/linuxmint.jpg /usr/share/backgrounds/linuxmint/default_background.jpg
gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/backgrounds/linuxmint/default_background.jpg'
