#!/bin/bash

update_background (){
    # Update the default BG date (to force a DE bg refresh on upgrade)
    if [ -e /usr/share/backgrounds/hamonikr/default_background.jpg ] ; then
        touch /usr/share/backgrounds/hamonikr/default_background.jpg
        touch /usr/share/cinnamon-background-properties/hamonikr.xml
    fi
}

case "$1" in
    configure|upgrade|update|reconfigure|triggered)
    
        update_background
        glib-compile-schemas /usr/share/glib-2.0/schemas
        
        if which update-icon-caches >/dev/null 2>&1 ; then
            update-icon-caches /usr/share/icons
        fi

        if [ -f "/etc/hamonikr/info" ] ; then
            echo "Update HamoniKR OS Wallpaper Setting..."

            xcheck=`tty | cut -d '/' -f3`
            if [ $xcheck == "pts" ]; then

                RUID=$(who | awk 'FNR == 1 {print $1}')
                RUSER_UID=$(id -u ${RUID})

                if [ ! -z "$RUID" ] ; then
                    # Set gsettings for the Real User
                    sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.background picture-uri "file:////usr/share/backgrounds/hamonikr/default_background.jpg"
                    sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.gnome.desktop.background picture-uri "file:////usr/share/backgrounds/hamonikr/default_background.jpg"
                    sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.mate.background picture-filename "file:////usr/share/backgrounds/hamonikr/default_background.jpg"                
                    sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set x.dm.slick-greeter background '/usr/share/backgrounds/hamonikr/default_background.jpg'
                fi
            
            fi

            # change lightdm setting
            if [ -f "/etc/lightdm/lightdm-gtk-greeter.conf.d/99_linuxmint.conf" ] ; then
                sed -i 's|background=/usr/share/backgrounds/linuxmint/default_background.jpg|background=/usr/share/backgrounds/hamonikr/default_background.jpg|g' \
                /etc/lightdm/lightdm-gtk-greeter.conf.d/99_linuxmint.conf
            fi        

            if [ -f "/etc/lightdm/slick-greeter.conf" ] ; then
                sed -i 's|background=/usr/share/backgrounds/linuxmint/default_background.jpg|background=/usr/share/backgrounds/hamonikr/default_background.jpg|g' \
                /etc/lightdm/slick-greeter.conf
            else
                echo -e "[Greeter]\nbackground=/usr/share/backgrounds/hamonikr/default_background.jpg" | sudo tee /etc/lightdm/slick-greeter.conf
            fi
          
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
