#!/bin/bash
### Getting OS Information
if [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    DIST=$DISTRIB_ID
    DIST_VER=$DISTRIB_RELEASE
else
    DIST="Unknown"
    DIST_VER="Unknown"
fi

if [ "$XDG_CURRENT_DESKTOP" = "" ]
then
  desktop=$(echo "$XDG_DATA_DIRS" | sed 's/.*\(xfce\|kde\|gnome\).*/\1/')
else
  desktop=$XDG_CURRENT_DESKTOP
fi
# convert to lower case
desktop=${desktop,,}

case $DIST in
    HamoniKR)
        echo "Process environment setting for HamoniKR OS..."

        # Get the Real Username
        RUID=$(who | awk 'FNR == 1 {print $1}')

        # Translate Real Username to Real User ID
        RUSER_UID=$(id -u ${RUID})

        # Set gsettings for the Real User
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.background picture-uri "file:////usr/share/backgrounds/HamoniKR/hamonikr-7.jpg"
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set x.dm.slick-greeter background '/usr/share/backgrounds/HamoniKR/hamonikr-8.jpg'
    ;;
    *)
    ;;
esac

echo "
If you have any questions, please feel free to visit the address below.

https://hamonikr.org
"
sleep 2

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons
	fi
fi
#DEBHELPER#
exit 0