#!/bin/bash

case "$1" in
    remove|upgrade|deconfigure)

      if [ -f "/etc/hamonikr/info" ] ; then

        xcheck=`tty | cut -d '/' -f3`
        if [ $xcheck == "pts" ]; then
          RUID=$(who | awk 'FNR == 1 {print $1}')
          RUSER_UID=$(id -u ${RUID})

          # Set gsettings for the Real User
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.background picture-uri 'file:////usr/share/backgrounds/linuxmint/default_background.jpg'
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set x.dm.slick-greeter background 'file:////usr/share/backgrounds/linuxmint/default_background.jpg'		
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.gnome.desktop.background picture-uri "file:////usr/share/backgrounds/linuxmint/default_background.jpg"
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.mate.background picture-filename "file:////usr/share/backgrounds/linuxmint/default_background.jpg"                        
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set x.dm.slick-greeter background '/usr/share/backgrounds/linuxmint/default_background.jpg'
        fi

        # change lightdm setting
        if [ -f "/etc/lightdm/lightdm-gtk-greeter.conf.d/99_linuxmint.conf" ] ; then
          sed -i 's|background=/usr/share/backgrounds/hamonikr/default_background.jpg|background=/usr/share/backgrounds/linuxmint/default_background.jpg|g' \
          /etc/lightdm/lightdm-gtk-greeter.conf.d/99_linuxmint.conf
        fi

      fi

    ;;
    failed-upgrade)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
